using System.Diagnostics;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace AxisTypes.SourceGenerator;

[Generator]
public class ValueObjectGenerator : IIncrementalGenerator
{
    private const string AttributeSource = """
// <auto-generated />
#nullable enable
namespace AxisTypes.SourceGenerator
{
    [global::System.AttributeUsage(global::System.AttributeTargets.Class | global::System.AttributeTargets.Struct, AllowMultiple = false, Inherited = false)]
    internal sealed class ValueObjectAttribute : global::System.Attribute
    {
        public string PropertyName { get; set; } = "Value";
        public bool ImplicitFromString { get; set; } = true;
        public bool TryParse { get; set; } = true;
        public bool CaseInsensitiveEquals { get; set; } = true;
        public bool UseInvariantCulture { get; set; } = false;
    }
}
""";


    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
            ctx.AddSource("ValueObjectAttribute.g.cs", AttributeSource));

        var typeInfos = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "AxisTypes.SourceGenerator.ValueObjectAttribute",
                predicate: static (node, _) => node is TypeDeclarationSyntax,
                transform: static (ctx, _) => ExtractTypeInfo(ctx))
            .Where(static t => t != null)
            .Select(static (t, _) =>
            {
                Debug.Assert(t != null, nameof(t) + " != null");
                return t.Value;
            });

        context.RegisterSourceOutput(typeInfos, static (spc, info) =>
            spc.AddSource($"{info.TypeName}.g.cs", GenerateCode(info)));
    }

    private static TypeInfo? ExtractTypeInfo(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol symbol)
            return null;

        var attr = ctx.Attributes.First();

        var propertyName = "Value";
        var implicitFromString = true;
        var tryParse = true;
        var caseInsensitiveEquals = true;
        var useInvariantCulture = false;

        foreach (var kvp in attr.NamedArguments)
        {
            switch (kvp.Key)
            {
                case "PropertyName":
                    propertyName = kvp.Value.Value as string ?? "Value";
                    break;
                case "ImplicitFromString":
                    implicitFromString = (bool)(kvp.Value.Value ?? true);
                    break;
                case "TryParse":
                    tryParse = (bool)(kvp.Value.Value ?? true);
                    break;
                case "CaseInsensitiveEquals":
                    caseInsensitiveEquals = (bool)(kvp.Value.Value ?? true);
                    break;
                case "UseInvariantCulture":
                    useInvariantCulture = (bool)(kvp.Value.Value ?? false);
                    break;
            }
        }

        return new TypeInfo
        {
            TypeName = symbol.Name,
            Namespace = symbol.ContainingNamespace.ToDisplayString(),
            IsValueType = symbol.IsValueType,
            IsRecord = symbol.IsRecord,
            IsReadOnly = symbol.IsReadOnly,
            PropertyName = propertyName,
            ImplicitFromString = implicitFromString,
            GenerateTryParse = tryParse,
            CaseInsensitiveEquals = caseInsensitiveEquals,
            UseInvariantCulture = useInvariantCulture,
        };
    }

    private static string GenerateCode(TypeInfo info)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {info.Namespace};");
        sb.AppendLine();

        var typeKeyword = GetTypeKeyword(info);
        sb.AppendLine($"public {typeKeyword} {info.TypeName}");
        sb.AppendLine("{");

        sb.AppendLine($"    public static implicit operator string({info.TypeName} value) => value.{info.PropertyName};");
        sb.AppendLine($"    public override string ToString() => {info.PropertyName};");

        if (info.ImplicitFromString)
            sb.AppendLine($"    public static implicit operator {info.TypeName}(string? value) => new(value);");

        if (info.CaseInsensitiveEquals)
        {
            var comparison = info.UseInvariantCulture ? "InvariantCultureIgnoreCase" : "OrdinalIgnoreCase";

            sb.AppendLine(info.IsValueType
                ? $"    public bool Equals({info.TypeName} other) => string.Equals({info.PropertyName}, other.{info.PropertyName}, global::System.StringComparison.{comparison});"
                : $"    public virtual bool Equals({info.TypeName}? other) => other is not null && string.Equals({info.PropertyName}, other.{info.PropertyName}, global::System.StringComparison.{comparison});");

            sb.AppendLine($"    public override int GetHashCode() => global::System.StringComparer.{comparison}.GetHashCode({info.PropertyName});");
        }

        if (info.GenerateTryParse)
        {
            var defaultValue = info.IsValueType ? "default" : "default!";
            sb.AppendLine();
            sb.AppendLine($"    public static bool TryParse(object? s) => TryParse(s, out _);");
            sb.AppendLine($"    public static bool TryParse(object? s, out {info.TypeName} result)");
            sb.AppendLine("    {");
            sb.AppendLine("        try");
            sb.AppendLine("        {");
            sb.AppendLine($"            result = new {info.TypeName}(s?.ToString());");
            sb.AppendLine("            return true;");
            sb.AppendLine("        }");
            sb.AppendLine("        catch");
            sb.AppendLine("        {");
            sb.AppendLine($"            result = {defaultValue};");
            sb.AppendLine("            return false;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string GetTypeKeyword(TypeInfo info)
    {
        if (info.IsValueType)
        {
            var ro = info.IsReadOnly ? "readonly " : "";
            return info.IsRecord
                ? $"{ro}partial record struct"
                : $"{ro}partial struct";
        }

        return info.IsRecord ? "partial record" : "partial class";
    }

    private struct TypeInfo
    {
        public string TypeName;
        public string Namespace;
        public bool IsValueType;
        public bool IsRecord;
        public bool IsReadOnly;
        public string PropertyName;
        public bool ImplicitFromString;
        public bool GenerateTryParse;
        public bool CaseInsensitiveEquals;
        public bool UseInvariantCulture;
    }

}
